export const projects = [
  {
    title: "Multi-Modal RAG Pipeline",
    description: "End-to-end retrieval-augmented generation system supporting text, images, and PDFs. Built with LangChain, ChromaDB, and GPT-4V for intelligent document Q&A.",
    tech: ["LangChain", "Python", "ChromaDB", "GPT-4V", "FastAPI"],
    demo: "#",
    github: "#",
    color: "#00d4ff",
  },
  {
    title: "Agentic AI Workflow Engine",
    description: "Multi-agent orchestration platform using LangGraph. Agents autonomously plan, execute, and self-correct complex tasks with persistent state and human-in-the-loop support.",
    tech: ["LangGraph", "LangSmith", "Python", "Redis", "Docker"],
    demo: "#",
    github: "#",
    color: "#7c3aed",
  },
  {
    title: "LangSmith Observability Dashboard",
    description: "Custom tracing and evaluation dashboard built on LangSmith. Visualises LLM traces, latency, token usage, and A/B test prompts across production pipelines.",
    tech: ["LangSmith", "Next.js", "FastAPI", "PostgreSQL", "Recharts"],
    demo: "#",
    github: "#",
    color: "#06ffa5",
  },
  {
    title: "MCP Tool Server",
    description: "Model Context Protocol server exposing custom tools to Claude and GPT-4o. Enables LLMs to call internal APIs, search databases, and execute code sandboxed in Docker.",
    tech: ["MCP", "Python", "Docker", "FastAPI", "TypeScript"],
    demo: "#",
    github: "#",
    color: "#00d4ff",
  },
  {
    title: "RAG-Powered Knowledge Base",
    description: "Enterprise knowledge assistant with hybrid search (dense + sparse). Ingests 10k+ documents, re-ranks with Cohere, and streams answers via a Next.js chat UI.",
    tech: ["LangChain", "Qdrant", "Cohere", "Next.js", "Python"],
    demo: "#",
    github: "#",
    color: "#7c3aed",
  },
  {
    title: "Dockerised AI Microservices",
    description: "Production-ready containerised architecture for Gen AI services. Includes autoscaling inference workers, GPU-aware scheduling, and a unified API gateway.",
    tech: ["Docker", "Python", "Kubernetes", "FastAPI", "NVIDIA "],
    demo: "#",
    github: "#",
    color: "#06ffa5",
  },
];

export const experience = [
  {
    role: "Gen AI Engineer",
    company: "AntiGravity Labs",
    period: "2023 – Present",
    description: "Architecting and deploying production Gen AI systems — RAG pipelines, agentic workflows, and LLM observability platforms for enterprise clients.",
    tech: ["LangChain", "LangGraph", "LangSmith", "Python", "Docker"],
  },
  {
    role: "AI/ML Engineer",
    company: "Nexus AI",
    period: "2021 – 2023",
    description: "Built and shipped NLP pipelines and fine-tuned LLMs for classification, summarisation, and semantic search across large document corpora.",
    tech: ["Python", "HuggingFace", "FastAPI", "PostgreSQL", "RAG"],
  },
  {
    role: "Python Developer",
    company: "DataFlow Systems",
    period: "2020 – 2021",
    description: "Developed ETL pipelines and REST APIs powering data ingestion for ML training platforms, focusing on scalability and data quality.",
    tech: ["Python", "FastAPI", "Docker", "Airflow", "SQL"],
  },
  {
    role: "IT Graduate",
    company: "Saveetha Engineering College",
    period: "2016 – 2020",
    description: "Bachelor of Technology in Information Technology",
    tech: ["Python", "Algorithms", "C++", "System Design"],
  },
];

export const skills = [
  { name: "Python", icon: "🐍" },
  { name: "LangChain", icon: "🔗" },
  { name: "LangGraph", icon: "🕸️" },
  { name: "LangSmith", icon: "🔬" },
  { name: "RAG", icon: "📚" },
  { name: "Multi-Modal RAG", icon: "🖼️" },
  { name: "Agentic AI", icon: "🤖" },
  { name: "Gen AI", icon: "✨" },
  { name: "MCP", icon: "⚡" },
  { name: "Docker", icon: "🐳" },
  { name: "FastAPI", icon: "🚀" },
  { name: "OpenAI API", icon: "🧠" },
  { name: "HuggingFace", icon: "🤗" },
  { name: "Vector DBs", icon: "🗄️" },
  { name: "Prompt Engineering", icon: "💬" },
  { name: "Next.js", icon: "▲" },
];
