export const projects = [
  {
    title: "Multi-Modal RAG Pipeline",
    description: "End-to-end retrieval-augmented generation system supporting text, images, and PDFs. Built with LangChain, ChromaDB, and GPT-4V for intelligent document Q&A.",
    tech: ["LangChain", "Python", "ChromaDB", "GPT-4V", "FastAPI"],
    demo: "#",
    github: "#",
    color: "#00d4ff",
  },
  {
    title: "Agentic AI Workflow Engine",
    description: "Multi-agent orchestration platform using LangGraph. Agents autonomously plan, execute, and self-correct complex tasks with persistent state and human-in-the-loop support.",
    tech: ["LangGraph", "LangSmith", "Python", "Redis", "Docker"],
    demo: "#",
    github: "#",
    color: "#7c3aed",
  },
  {
    title: "LangSmith Observability Dashboard",
    description: "Custom tracing and evaluation dashboard built on LangSmith. Visualises LLM traces, latency, token usage, and A/B test prompts across production pipelines.",
    tech: ["LangSmith", "Next.js", "FastAPI", "PostgreSQL", "Recharts"],
    demo: "#",
    github: "#",
    color: "#06ffa5",
  },
  {
    title: "MCP Tool Server",
    description: "Model Context Protocol server exposing custom tools to Claude and GPT-4o. Enables LLMs to call internal APIs, search databases, and execute code sandboxed in Docker.",
    tech: ["MCP", "Python", "Docker", "FastAPI", "TypeScript"],
    demo: "#",
    github: "#",
    color: "#00d4ff",
  },
  {
    title: "RAG-Powered Knowledge Base",
    description: "Enterprise knowledge assistant with hybrid search (dense + sparse). Ingests 10k+ documents, re-ranks with Cohere, and streams answers via a Next.js chat UI.",
    tech: ["LangChain", "Qdrant", "Cohere", "Next.js", "Python"],
    demo: "#",
    github: "#",
    color: "#7c3aed",
  },
  {
    title: "Dockerised AI Microservices",
    description: "Production-ready containerised architecture for Gen AI services. Includes autoscaling inference workers, GPU-aware scheduling, and a unified API gateway.",
    tech: ["Docker", "Python", "Kubernetes", "FastAPI", "NVIDIA "],
    demo: "#",
    github: "#",
    color: "#06ffa5",
  },
];

export const experience = [
  {
    role: "Gen AI Engineer",
    company: "HireEva by StelleHire ",
    period: "Apr 2025 – Present",
    description: "Developed conversation Ai interviewing platform. Architecting and deploying production Gen AI systems — RAG pipelines, agentic workflows, and LLM observability platforms for enterprise clients.",
    tech: ["LangChain", "LangGraph", "LangSmith", "Python", "Docker","multi-agent orchestration"],
  },
  {
    role: "Software Developer ",
    company: "TVS Credit",
    period: "Jun 2023 – Apr 2025",
    description: "Developed and maintained features for various communication channel applications including SMS , WA , Email",
    tech: ["SQL", "PL/SQL", "FastAPI", "PostgreSQL","Reactjs"],
  },
  {
    role: "SDE Trainee",
    company: "Upgrad Knowledgehut",
    period: "Mar 2022 – Apr 2023",
    description: ".",
    tech: ["Reactjs", "MongoDB", "Javascript", "expressjs", "nodejs"],
  },
  // {
  //   role: "Forntend Developer",
  //   company: "Stellehire",
  //   period: "Apr 2021 – May 2022",
  //   description: "WordPress developer.",
  //   tech: ["Wordpress"],
  // },
  {
    role: "IT Graduate",
    company: "Saveetha Engineering College",
    // period: "2016 – 2020",
    description: "Bachelor of Technology in Information Technology",
    tech: ["Python", "Algorithms", "javascript","Java", "System Design","networking","compiler design", "data structures"],
  },
];

export const skills = [
  { name: "Python", icon: "🐍" },
  { name: "LangChain", icon: "🔗" },
  { name: "LangGraph", icon: "🕸️" },
  { name: "LangSmith", icon: "🔬" },
  { name: "RAG", icon: "📚" },
  { name: "Multi-Modal RAG", icon: "🖼️" },
  { name: "Agentic AI", icon: "🤖" },
  { name: "Gen AI", icon: "✨" },
  { name: "MCP", icon: "⚡" },
  { name: "Docker", icon: "🐳" },
  { name: "FastAPI", icon: "🚀" },
  { name: "OpenAI API", icon: "🧠" },
  { name: "HuggingFace", icon: "🤗" },
  { name: "Vector DBs", icon: "🗄️" },
  { name: "Prompt Engineering", icon: "💬" },
  { name: "Next.js", icon: "▲" },
];
